  ; PXE DEMO - Scrolling a 5 screen wide scene with paddle controller
  ; Demonstrates using paddles and scrolling a large playfield horizontally

  ; Tell bB to use the PXE kernel
  set kernel PXE

  ; Set Playfield mode to use the same Fractional Increment, and Scrolling registers 
  ; for COLUBK, COLUPF, and all PF columns
  ; Set the Playfield buffer width to the full 120 PF pixels
  PF_MODE = $ff

  ; Disable Fractional Increment to give full 176 line height
  PF_FRAC_INC = 0

  ; Configure the paddle reading to return a value in the range 0-160 inclusive
  PaddleRange0 = 160 

  ; PXE has 3 screen wide PF buffer. There are 5 screens total to scroll through, so only the third will remain unchanged
  ; Copy the 3rd screen of the image into the 3rd screen of the PF buffer
  PF_WRITE_INDEX = 10 ; 5 columns of 8 PF pixels per screen. 10th column is beginning of 3rd screen
  gosub __sub_Skyline3

__Main_Loop
  ; Set the 16 bit scroll position to Paddle0 value * 4
  PF_HOR_SCROLL_LO = Paddle0 * 4
  PF_HOR_SCROLL_HI = Paddle0 / 64

  ; Update left 2 screens of PF buffer based on scroll offset
  PF_WRITE_INDEX = 0
  if Paddle0 < 80 then gosub __sub_Skyline12 ; Screens 1 and 2 of image
  if Paddle0 > 79 then gosub __sub_Skyline45 ; Screens 4 and 5 of image

  drawscreen
  goto __Main_Loop

; STOP READING HERE - Remaing code is generated via python script parsing the playfield png

; **************** BEGIN AUTO GENERATED - DO NOT EDIT ****************
__sub_Skyline12
  bkcolors:
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
end
  pfcolors:
  $00
  $00
  $00
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
end
  playfield:
  ................................................................................
  ................................................................................
  ................................................................................
  ........X.......................................................................
  ........X.......................................................................
  ........X...........................................................X...........
  ........X...........................................................X...........
  .......XXX..........................................................X...........
  .......XXX..........................................................X...........
  .......XXX..........................................................X...........
  .......XXX..........................................................X...........
  ......XXXXX.........................................................X...........
  ......XXXXX..............X..........................................X...........
  ......XXXXX..............X..........................................X...........
  ......XXXXX..............X..........................................X...........
  .....XXXXXXX.............XX.........................................X...........
  .....XXXXXXX.............XX.........................................X...........
  .....XXXXXXX.............XX.........................................X...........
  .....XXXXXXX.............XXX........................................X...........
  .....XXXXXXX.............XXX......................XXXXXXX...........X...........
  .....XXXXXXX.............XXX......................XXXXXXX...........X...........
  .....XXXXXXX.............XXXX.....................XXXXXXX...........X...........
  .....XXXXXXX.............XXXX.....................XXXXXXX...........X...........
  .....XXXXXXX.............XXXX.....................XXXXXXX..........XXX..........
  .....XXXXXXX.............XXXX.....................XXXXXXX..........XXX..........
  .....X..X..X.............XXXX.....................XXXXXXX..........XXX..........
  .....X..X..X.............XXXX.....................XXXXXXX..........XXX..........
  .....X..X..X.............XXXX.....................XXXXXXX.........XXXXX.........
  .....X..X..X.............XXXX.....................X.X.X.X.........XXXXX.........
  .....X..X..X.............XXXX.....................X.X.X.X.........XXXXX.........
  .....X..X..X.............XXXX.....................X.X.X.X.........XXXXX.........
  .....X..X..X.............X..X.....................X.X.X.X........XXXXXXX........
  ..X..X..X..X.............X..X.....................X.X.X.X........XXXXXXX........
  ..X..X..X..X.............X..X.....................X.X.X.X.......................
  .XXX.X..X..X.............X..X.....................X.X.X.X........X.X.X.X........
  .XXX.X..X..X.............X..X.....................XXXXXXX........X.X.X.X........
  .XXX.X..X..X.......XXXX..X..X.....................XXXXXXX........X.X.X.X........
  .XXX.X..X..X.......XXXX..X..X.....................XXXXXXX........X.X.X.X........
  .XXX.X..X..X.......XXXX..X..X.....................XXXXXXX........X.X.X.X........
  .XXX.XXXXXXX.......XXXX..XXXX.....................XXXXXXX.......................
  .XXX.XXXXXXX.......XXXX..XXXX.....................XXXXXXX........XXXXXXX........
  .XXX.XXXXXXX.......XXXX..XXXX.....................XXXXXXX........XXXXXXX........
  .XXX.XXXXXXX.......XXXX..XXXX.....................X.X.X.X.........XXXXX.........
  .XXX.XXXXXXX.......XXXX..XXXX.....................X.X.X.X.........XXXXX.........
  .XXX.XXXXXXX.......XXXX..XXXX.....................X.X.X.X.........XXXXX.........
  .XXX.XXXXXXX.......XX.X..XXXX.....................X.X.X.X.........XXXXX.........
  .XXX.XXXXXXX.......XX.X..XXXX.....................X.X.X.X..........XXX..........
  .XXX.XXXXXXX.......XX.X..X..X.....................X.X.X.X..........XXX..........
  .XXX.X..X..X.......XX.X..X..X.....................X.X.X.X..........XXX..........
  .X.X.X..X..X.......XX.X..X..X.....................XXXXXXX..........XXX..........
  .X.X.X..X..X.......XX.X..X..X.....................XXXXXXX...........X...........
  .X.X.X..X..X.......XX.X..X..X.XXXXXXXXXX..........XXXXXXX...........X...........
  .X.X.X..X..X.......X.XX..X..X.XXXXXXXXXX..........XXXXXXX...........X...........
  .X.X.X..X..X.......X.XX..X..X.XXXXXXXXXX..........XXXXXXX...........X...........
  .X.X.X..X..X.......X.XX..X..X.XXXXXXXXXX..........XXXXXXX...........X...X..X....
  .X.X.X..X..X.......X.XX..XXXX.XXXXXXXXXX..........XXXXXXX...........X...X..X....
  .....X..X..X.......X.XX..XXXX.XXXXXXXXXX..........X.X.X.X...........X...X..X....
  XXXXXX..X..X.......X.XX..XXXX.XXXXXXXXXX..........X.X.X.X...........X...XX.XX...
  XXXXXX..X..X.......X.XX..XXXX.XXXXXXXXXX..........X.X.X.X...........X...XX.XX...
  XXXXXX..X..X.......XX.X..XXXX.X..X..X..X..........X.X.X.X...........X...XX.XX...
  XXXXXX..X..X.......XX.X..XXXX.X..X..X..X..........X.X.X.X...........X...XXXXXX..
  XXXXXX..X..X.......XX.X..XXXX.X..X..X..X..........X.X.X.X...........X...XXXXXX..
  XXXXXXXXXXXX...X...XX.X..XXXX.X..X..X..X..........X.X.X.X...........X...XXXXXX..
  XXXXXXXXXXXX..XXX..XX.X..X..X.X..X..X..X..........XXXXXXX...........X...XXXXXXX.
  XXXXXXXXXXXX..XXX..XX.X..X..X.X..X..X..X..........XXXXXXX...........X...XXXXXXX.
  XXXXXXXXXXXX.XXXXX.XX.X..X..X.X..X..X..X..........XXXXXXX...........X...XXXXXXX.
  X.X.XXXXXXXX.XXXXX.X.XX..X..X.X..X..X..X..........XXXXXXX...........X...XXXXXXX.
  X.X.XXXXXXXXXXXXXXXX.XX..X..X.X..X..X..X..........XXXXXXX...........X...XXXXXXX.
  X.X.XXXXXXXXXXXXXXXX.XX..X..X.X..X..X..X..........XXXXXXX...........X...XXXXXXX.
  X.X.XXXXXXXXXXXXXXXX.XX..X..X.X..X..X..X..........XXX...............X...XXXXXXX.
  X.X.XXXXXXXXXXXXXXXX.XX..X..X.X..X..X..X..........X.X...............X...XXXXXXX.
  X.X.XX..X..XXXXXXXXX.XX..XXXX.X..X..X..X..........X.XXXXXXXXXXX.....X...XXXXXXX.
  X.X.XX..X..XXXXXXXXX.XX..XXXX.X..X..X..X..........X.XXXXXXXXXXX.....X...XXXXXXX.
  XXXXXX..X..XXXXXXXXXX.X..XXXX.XXXXXXXXXX..........X.XXXXXXXXXXX.....X...X..X..X.
  XXXXXX..X..XXXXXXXXXX.X..XXXX.XXXXXXXXXX..........X.XXXXXXXXXXX.....X...X..X..X.
  XXXXXX..X..XXXXXXXXXX.X..XXXX.XXXXXXXXXX..........X.XXXXXXXXXXX.....X...X..X..X.
  XXXXXX..X..XXXXXXXXXX.X..XXXX.XXXXXXXXXX..........X.XXXXXXXXXXX.....X...X..X..X.
  XXXXXX..X..XXXXXXXXXX.X..XXXX.XXXXXXXXXX..........XXXX..X..X..X.....X...X..X..X.
  XXXXXX..X..XXXXXXXXXX.X..XXXX.XXXXXXXXXX..XX......XXXX..X..X..X.....X...X..X..X.
  XXXXXX..X..XXXXXXXXXX.X..X..X.X..X..X..X..XX......XXXX..X..X..X.....X...X..X..X.
  X.X.XX..X..XX.X.X.XX.XX..X..X.X..X..X..X.XXXX.....XXXX..X..X..X.....X...X..X..X.
  X.X.XX..X..XX.X.X.XX.XX..X..X.X..X..X..X.XXXX.....XXXX..X..X..X.....X...XXXXXXX.
  X.X.XX..X..XX.X.X.XX.XX..X..X.X..X..X..XXXXXXX....XXXX..X..X..X.....X...XXXXXXX.
  X.X.XX..X..XX.X.X.XX.XX..X..X.X..X..X..XXXXXXX....XXXX..X..X..X.....X...XXXXXXX.
  X.X.XX..X..XX.X.X.XX.XX..X..X.X..X..X..XXXXXXX....X.XX..X..X..X.....X...XXXXXXX.
  X.X.XXXXXXXXX.X.X.XX.XX..X..X.X..X..X..XXXXXXX....X.XX..X..X..X.....X...XXXXXXX.
  X.X.XXXXXXXXX.X.X.XX.XX..X..X.X..X..X..XXXXXXX....X.XX..X..X..X....X.X..XXXXXXX.
  XXXXXXXXXXXXXXXXXXXXX.X..XXXX.X..X..X..XXXXXXX....X.XX..X..X..X....X.X..XXXXXXX.
  XXXXXXXXXXXXXXXXXXXXX.X..XXXX.X..X..X..XXXXXXX....X.XX..X..X..X....X.X..XXXXXXX.
  XXXXXXXXXXXXXXXXXXXXX.X..XXXX.X..X..X..XXXXXXX....X.XX..X..X..X....X.X..X..X..X.
  XXXXXXXXXXXXXXXXXXXXX.X..XXXX.X..X..X..XXXXXXX....X.XX..X..X..X.....X...X..X..X.
  XXXXXXXXXXXXXXXXXXXXX.X..XXXX.X..X..X..XX....X....XXXXXXXXXXXXX.....X...X..X..X.
  XXXXXXXXXXXXXXXXXXXXX.X..XXXX.X..X..X..XX....X....XXXXXXXXXXXXX.....X...X..X..X.
  XXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXX....X....XXXXXXXXXXXXX.....X...X..X..X.
  X.X.XX..X..XX.X.X.X...........XXXXXXXXXXX....X....XXXXXXXXXXXXX....X.X..X..X..X.
  X.X.XX..X..XX.X.X.XXXXXXXXXXXXXXXXXXXXXXX....X....XXXXXXXXXXXXX....X.X..X..X..X.
  X.X.XX..X..XX.X.X.XXXXXXXXXXXXXXXXXXXXXXX....X.......XXXXXXXXXX....X.X..X..X..X.
  X.X.XX..X..XX.X.X.XXXXXXXXXXXXXXXXXXXXXXX....X.......X..X..X..X....X.X..XXXXXXX.
  X.X.XX..X..XX.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..X..X..X.....X...XXXXXXX.
  X.X.XX..X..XX.X.X.XXXXXXXXXXXXX..X..X..XXXXXXXXXXXXXXX..X..X..X.....X...XXXXXXX.
  X.X.XX..X..XX.X.X.XXXXXXXXXXXXX..X..X..XXXXXXXXXXXXXXX..X..X..X.....X...XXXXXXX.
  XXXXXX..X..XXXXXXXXXXXXXXXXXXXX..X..X..XXXXXXXXXXXXXXX..X..X..X.....X...XXXXXXX.
  XXXXXX..X..XXXXXXXXXXXXXXXXXXXX..X..X..XXXXXXXXXXXXXXX..X..X..X....X.X..XXXXXXX.
  XXXXXX..X..XXXXXXXXX.X.X.X.X.XX..X..X..XXXXXXXXXXXXXXX..X..X..X....X.X..XXXXXXX.
  XXXXXX..X..XXXXXXXXX.X.X.X.X.XX..X..X..XXXXXXXXXXXXXXX..X..X..X....X.X..XXXXXXX.
  XXXXXX..X..XXXXXXXXX.X.X.X.X.XX..X..X..XX....XXXXXXXXX..X..X..X....X.X..X..X..X.
  XXXXXX..X..XXXXXXXXX.X.X.X.X.XX..X..X..XX....XX.X.X.XX..X..X..X.....X...X..X..X.
  XXXXXX..X..XXXXXXXXX.X.X.X.X.XX..X..X..XX....XX.X.X.XX..X..X..X.....X...X..X..X.
  X.X.XXXXXXXXX.X.X.XX.X.X.X.X.XX..X..X..XX....XX.X.X.XX..X..X..X.....X...X..X..X.
  X.X.XXXXXXXXX.X.X.XX.X.X.X.X.XX..X..X..XX....XX.X.X.XX..X..X..X.....X...X..X..X.
  X.X.XXXXXXXXX.X.X.XX.X.X.X.X.XX..X..X..XX....XX.X.X.XX..X..X..X....XXX..X..X..X.
  X.X.XXXXXXXXX.X.X.XX.X.X.X.X.XX..X..X..XX....XX.X.X.XXXXXXXXXXX....XXX..X..X..X.
  X.X.XXXXXXXXX.X.X.XX.X.X.X.X.XX..X..X..XXXXXXXX.X.X.XXXXXXXXXXX....XXX..X..X..X.
  X.X.XXXXXXXXX.X.X.XX.X.X.X.X.XXXXXXXXXXXXXXXXXX.X.X.XXXXXXXXXXX....XXX..XXXXXXX.
  X.X.XXXXXXXXX.X.X.XX.X.X.X.X.XXXXXXXXXXXXXXXXXX.X.X.XXXXXXXXXXX....XXX..XXXXXXX.
  XXXXXXXXXXXXXXXXXXXX.X.X.X.X.XXXXXXXXXXXXXXXXXX.X.X.XXXXXXXXXXX....XXX..XXXXXXX.
  XXXXXXXXXXXXXXXXXXXX.X.X.X.X.XXXXXXXXXXXXXXXXXX.X.X.XXXXXXXXXXX....XXX..XXXXXXX.
  XXXXXXXXX..XXXXXXXXX.X.X.X.X.XXXXXXXXXXXXXXXXXX.X.X.XX..X..X..X....XXX..XXXXXXX.
  XXXXXXXXX..XXXXXXXXX.X.X.X.X.XXXXXXXXXXXXXXXXXX.X.X.XX..X..X..X....XXX..XXXXXXX.
  XXXXXXXXX..XXXXXXXXXXXXXXXXXXXX..X..X..XX....XX.X.X.XX..X..X..X....XXX..XXXXXXX.
  XXXXXXXXX..XXXXXXXXXXXXXXXXXXXX..X..X..XX....XX.X.X.XX..X..X..X....XXX..XXXXXXX.
  XXXXXXXXX..XXXXXXXXXXXXXXXXXXXX..X..X..XX....XX.X.X.XX..X..X..X....XXX..X..X..X.
  ........X..XX.X.X.XXXXXXXXXXXXX..X..X..XX....XXXXXXXXX..X..X..X....XXX..X..X..X.
  ........X..XX.X.X.XXXXXXXXXXXXX..X..X..XX....XXXXXXXXX..X..X..X....X.X..X..X..X.
  XXXXXXXXX..XX.X.X.XXXXXXXXXXXXX..X..X..XX....XXXXXXXXX..X..X..X....X.X..X..X..X.
  XXXXXXXXX..XX.X.X.XXXXXXXXXXXXX..X..X..XX....XXXXXXXXX..X..X..X....X.X..X..X..X.
  XXXXXXXXX..XX.X.X.XXXXXXXXXXXXX..X..X..XXXXXXXXXXXXXXX..X..X..X....X.X..X..X..X.
  XXXXXXXXX..XX.X.X.XX.X.X.X.X.XX..X..X..XXXXXXXXXXXXXXX..X..X..X....X.X..X..X..X.
  XXXXXXXXX..XX.X.X.XX.X.X.X.X.XX..X..X..XXXXXXXXXXXXXXX..X..X..X....X.X..X..X..X.
  XXXXXXXXX..XXXXXXXXX.X.X.X.X.XX..X..X..XXXXXXXXXXXXXXX..X..X..X....X.X..XXXXXXX.
  XXXXXXXXX..XXXXXXXXX.X.X.X.X.XX..X..X..XXXXXXXX.X.X.XX..X..X..X....X.X..XXXXXXX.
  XXXXXXXXXXXXXXXXXXXX.X.X.X.X.XX..X..X..XXXXXXXX.X.X.XXXXXXXXXXX....XXX..XXXXXXX.
  X..XX..XXXXXXXXXXXXX.X.X.X.X.XX..X..X..XXXXXXXX.X.X.XXXXXXXXXXX....XXX..XXXXXXX.
  X..XX..XXXXXXXXXXXXX.X.X.X.X.XXXXXXXXXXXX....XX.X.X.XXXXXXXXXXX....XXX..XXXXXXX.
  X..XX..XXXXXXXXXXXXX.X.X.X.X.XXXXXXXXXXXX....XX.X.X.XXXXXXXXXXX....XXX..XXXXXXX.
  X..XX..XXXXXXXXXXXXX.X.X.X.X.XXXXXXXXXXXX....XX.X.X.XXXXXXXXXXX....XXX..XXXXXXX.
  X..XX..XX................X.X.XXXXXXXXXXXX....XX.X.X.XXXXXXXX.......XXX..........
  X..XX..XX................X.X.XXXXXXXXXXXX....XX.X.X.XX..X..X.......XXX..........
  X..XX..XXXXXXXXXXXXXXXXXXX.X.XXXXXXXXXXXX....XX.X.X.XX..X..XXXXXXXXXXXXXXXXXXXXX
  X..XX..XXXXXXXXXXXXXXXXXXX.X.XX..X..X..XX....XX.X.X.XX..X..XXXXXXXXX.XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX.X.XX..X..X..XXXXXXXX.X.X.XX..X..XXXXXXXXX.XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX.X.XX..X..X..XXXXXXXX.X.X.XX..X..XXXXXXXXX.XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX.X.XX..X..X..XXXXXXXX.X.X.XX..X..XXXXXXXXX.XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..X..X..XXXXXXXX.X.X.XX..X..XXXXXXXXX.XXXXXXXXXXX
  XXX..XXXXXXXXXXXXXXXXXXXXXXXXXX..X..X..XXXXXXXX.X.X.XX..X..XXXXXXXXX.XXXXXXXXXXX
  XXX..XXXXXXXXXXXXXXXXXXXXXXXXXX..X..X..XXXXXXXX.X.X.XX..X..XXXXXXXXX.XXXXXXXXXXX
  XXX..XXXXX..X..X..X..X..XXXXXXX..X..X..XXXXXXXXXXXXXXX..X..XX..X..XX.XX..X..X..X
  XXX..XXXXX..X..X..X..X..XXXXXXX..X..X..XX....XXXXXXXXX..X..XX..X..XXXXX..X..X..X
  XXX..XXXXX..X..X..X..X..XXXXXXX..X..X..XX....XXXXXXXXX..X..XX..X..XXXXX..X..X..X
  XXX..XXXXX..X..X..X..X..XXXXXXX..X..X..XX....XXXXXXXXX..X..XX..X..XXXXX..X..X..X
  XXX..XXXXX..X..X..X..X..XXXXXXX..X..X..XX....XXXXXXXXX..X..XX..X..XXXXX..X..X..X
  XXX..XXXXX..X..X..X..X..XX.X.XX..X..X..XX....XXXXXXXXXXXXXXXX..X..XXXXX..X..X..X
  XXXXXXXXXX..X..X..X..X..XX.X.XX..X..X..XX....XXXXXXXXXXXXXXXX..X..XXXXX..X..X..X
  XXXXXXXXXX..X..X..X..X..XX.X.XXXXXXXXXXXX....XXXXXXXXXXXXXXXX..X..XXXXX..X..X..X
  XXXXXXXXXXXXXXXXXXXXXXXXXX.X.XXXXXXXXXXXXXXXXXX.X.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXX.X.XXXXXXXXXXXXXXXXXX.X.X.XXXXXXXXXXXXXXXX.XXXXXXXXXXX
  X..XX..XXXXXXXXXXXXXXXXXXX.X.XXXXXXXXXXXXXXXXXX.X.X.XXXXXXXXXXXXXXXX.XXXXXXXXXXX
  X..XX..XXXXXXXXXXXXXXXXXXX.X.XXXXXXXXXXXXXXXXXX.X.X.XXXXXXXXXXXXXXXX.XXXXXXXXXXX
  X..XX..XXX..X..X..X..X..XX.X.XXXXXXXXXXXXXXXXXX.X.X.XXXXXXXXX..X..XX.XX..X..X..X
  X..XX..XXX..X..X..X..X..XX.X.XXXXXXXXXXXXXXXXXX.X.X.XXXXXXXXX..X..XX.XX..X..X..X
  X..XX..XXX..X..X..X..X..XX.X.XXXXXXXXXXXXXXXXXX.X.X.XXXXXXXXX..X..XX.XX..X..X..X
  X..XX..XXX..X..X..X..X..XX.X.XXXXXXXXXXXX....XXXXXXXXXXXXXXXX..X..XX.XX..X..X..X
  X..XX..XXX..X..X..X..X..XX.X.XXXXXXXXXXXX....XXXXXXXXXXXXXXXX..X..XX.XX..X..X..X
  X..XX..XXX..X..X..X..X..XX.X.XXXXXXXXXXXX....XXXXXXXXXXXXXXXX..X..XXXXX..X..X..X
  XXXXXXXXXX..X..X..X..X..XX.X.XXXXXXXXXXXX....XXXXXXXXXXXXXXXX..X..XXXXX..X..X..X
  XXXXXXXXXX..X..X..X..X..XX.X.XXXXXXXXXXXX....XXXXXXXXXXXXXXXX..X..XXXXX..X..X..X
  XXXXXXXXXXXXXXXXXXXXXXXXXX.X.XXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
end
  return
__sub_Skyline3
  bkcolors:
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
end
  pfcolors:
  $00
  $00
  $00
  $00
  $00
  $00
  $00
  $00
  $00
  $00
  $00
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
end
  playfield:
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........................................
  ........X.X.............................
  ........X.X.............................
  ........X.X.............................
  ........X.X.............................
  ........X.X.............................
  ........X.X.............................
  ........X.X.............................
  ........X.X.............................
  .......XXXXX............................
  .......XXXXX............................
  .......XXXXX.......................X....
  .......XXXXX...............XXX.....X....
  .......XXXXX...............XXX.....X....
  .......XXXXX.............XXXXXXX...X....
  .......XXXXX.............XXXXXXX..XX....
  .......XXXXX.............XXXXXXX..XX....
  .......XXXXX............XXXXXXXXX.XX....
  .......XXXXX............XXXXXXXXX.XX....
  .......XXXXX............XXX...XXXXXX....
  .......XXXXX...........XXXX...XXXXXX....
  .......XXXXX...........XXXX.X.XXXXXX....
  .......XXXXX...........XXXX.X.XXXXXX....
  .......XXXXX...........XXXX.X.XXXXXX....
  .......X.X.X..........XXXXX.X.XXXXXXX...
  .......X.X.X..........XXXXX.X.XXXXXXX...
  .......X.X.X..........XXXXX.X.XXXXXXX...
  .......X.X.X..........XXXXX.X.XXXXXXX...
  .......X.X.X..........XXXXX...XXXX..X...
  .......X.X.X..........XXXXX...XXXX..X...
  .......X.X.X..........XXXXX.XXXXXXXXX...
  .......X.X.X...........XXXX.XXXXXXXX....
  .......X.X.X...........XXXX.XXXXXXXX....
  .......X.X.X...........XXXX.XXXXXXXX....
  .......X.X.X...........XXXX.XXXXXXXX....
  .......X.X.X............XXXXXXXXXXXX....
  .......X.X.X............XXXXXXXXX.XX....
  .......X.X.X............XXXXXXXXX.XX....
  .......XXXXX.............XXXXXXX..XX....
  .......XXXXX.............XXXXXXX...X....
  .......XXXXX.............XXXXXXX...X....
  .......XXXXX.XXXXXXX.......XXX.....X....
  .......XXXXX.XXXXXXX...............X....
  .........XXX.XXXXXXX.......X.X..........
  .........XXX.XXXXXXX.......X.X..........
  ..XXXXXXXX.X.XXXXXXX.......X.X..........
  ..XXXXXXXX.X.XXXXXXX.......X.X..........
  ..XXXXXXXX.X.XXXXXXX.......X.X..........
  ..XXXXXXXX.X.XXXXXXX.......X.X..........
  ..XXXXXXXX.X.X..X..X.......XXX..........
  ..XXXXXXXX.X.X..X..X.......XXX..........
  ..XXXXXXXX.X.X..X..X.......XXX..........
  ..XXXXXXXX.X.X..X..X........X...........
  ..X.X.X.XX.X.X..X..X....................
  ..X.X.X.XX.X.X..X..X....................
  ..X.X.X.XX.X.X..X..X....................
  ..X.X.X.XX.X.X..X..X....................
  ..X.X.X.XX.X.X..X..X....................
  ..X.X.X.XX.X.X..X..X....................
  ..X.X.X.XXXX.X..X..X....................
  ..XXXXXXXXXX.X..X..X....................
  ..XXXXXXXXXX.X..X..X....................
  ..XXXXXXXXXX.X..X..X....................
  ..XXXXXXXXXX.XXXXXXX....................
  ..XXXXXXXXXX.XXXXXXX....................
  ..XXXXXXXXXX.XXXXXXX....................
  ..XXXXXXXX.X.XXXXXXX....................
  ..X.X.X.XX.X.XXXXXXX....................
  ..X.X.X.XX.X.XXXXXXX....................
  ..X.X.X.XX.X.X..X..X....................
  ..X.X.X.XX.X.X..X..X....................
  ..X.X.X.XX.X.X..X..X....................
  ..X.X.X.XX.X.X..X..X....................
  ..X.X.X.XX.X.X..X..X......XXXXXXX.......
  ..XXXXXXXX.X.X..X..X......XXXXXXX.......
  ..XXXXXXXX.X.X..X..X......XXXXXXX.......
  ..XXXXXXXX.X.X..X..X......XXXXXXX.......
  ..XXXXXXXX.X.X..X..X......XXXXXXX.......
  ..XXXXXXXX.X.X..X..X......XXXXXXX.......
  ..XXXXXXXX.X.X..X..X......XXXXXXX.......
  ..XXXXXXXXXX.X..X..X......XXXXXXX.......
  ..X.X.X.XXXX.X..X..X......X.X.X.X.......
  ..X.X.X.XXXX.X..X..X......X.X.X.X.......
  ..X.X.X.XXXX.XXXXXXX......X.X.X.X.......
  ..X.X.X.XXXX.XXXXXXX......X.X.X.X.......
  ..X.X.X.XXXX.XXXXXXX......X.X.X.XXXXXXXX
  ..X.X.X.XXXX.XXXXXXX......X.X.X.XXXXXXXX
  ..X.X.X.XX.X.XXXXXXX......X.X.X.XXXXXXXX
  ..XXXXXXXX.X.XXXXXXX......XXXXXXXXXXXXXX
  ..XXXXXXXX.X.X..X..X......XXXXXXXXXXXXXX
  ..XXXXXXXX.X.X..X..X......XXXXXXXXXXXXXX
  ..XXXXXXXX.X.X..X..X......XXXXXXXXXXXXXX
  ..XXXXXXXX.X.X..X..X......XXXXXXXXXXXXXX
  ..XXXXXXXX.X.X..X..X......XXXXXXXXXXXXXX
  .............X..X..X......XXXXXXXXXXXXXX
  .............X..X..X......X.X.X.XX..X..X
  XXXXXXXXXXXXXX..X..X......X.X.X.XX..X..X
  XXXXXXXXXXXXXX..X..X......X.X.X.XX..X..X
  XXXXXXXXXXXXXX..X..X......X.X.X.XX..X..X
  XXXXXXXXXXXXXX..X..X......X.X.X.XX..X..X
  XXXXXXXXXXXXXX..X..X......X.X.X.XX..X..X
  XXXXXXXXXXXXXX..X..X......X.X.X.XX..X..X
  XXXXXXXXXXXXXX..X..X......XXXXXXXX..X..X
  XXXXXXXXXXXXXXXXXXXX......XXXXXXXXXXXXXX
  X.X.X.X.X.X.XXXXXXXX......XXXXXXXXXXXXXX
  X.X.X.X.X.X.XXXXXXXX......XXXXXXXXXXXXXX
  X.X.X.X.X.X.XXXXXXXX......XXXXXXXXXXXXXX
  X.X.X.X.X.X.XXXXX.............XXXXXXXXXX
  X.X.X.X.X.X.XXXXX.............XXXXXXXXXX
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXX.XXXXXXXX
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXX.XXXXXXXX
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXX.XX..X..X
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXX.XX..X..X
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXX.XX..X..X
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXX.XX..X..X
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXX.XX..X..X
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXXXXX..X..X
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXXXXX..X..X
  X.X.X.X.X.X.XX..XX...X...X...XXXXX..X..X
  X.X.X.X.X.X.XX..XX...X...X...XXXXXXXXXXX
  XXXXXXXXXXXXXX..XX...X...X...XXXXXXXXXXX
  XXXXXXXXXXXXXX..XX...X...X...XXXXXXXXXXX
  XXXXXXXXXXXXXX..XX...X...X...XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX...X...X...XX.XXXXXXXX
  XXXXXXXXXXXXXXXXXX...X...X...XX.XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XX..X..X
  X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXX.XX..X..X
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXX.XX..X..X
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXXXXX..X..X
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXXXXX..X..X
  X.X.X.X.X.X.XX..XX...X...X...XXXXX..X..X
  X.X.X.X.X.X.XX..XX...X...X...XXXXX..X..X
  X.X.X.X.X.X.XX..XX...X...X...XXXXX..X..X
  X.X.X.X.X.X.XX..XX...X...X...XXXXXXXXXXX
  X.X.X.X.X.X.XX..XX...X...X...XXXXXXXXXXX
  X.X.X.X.X.X.XX..XX...X...X...XX.XXXXXXXX
  X.X.X.X.X.X.XX..XX...X...X...XX.XXXXXXXX
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXX.XXXXXXXX
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXX.XXXXXXXX
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXX.XXXXXXXX
  X.X.X.X.X.X.XX..XXXXXXXXXXXXXXX.XXXXXXXX
  X.X.X.X.X.X.XXXXXXXXXXXXXXXXXXX.XX..X..X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..X..X
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..X..X
  XXXXXXXXXXXXXXXXXX...X...X...XXXXX..X..X
  XXXXXXXXXXXXXXXXXX...X...X...XXXXX..X..X
  XXXXXXXXXXXXXXXXXX...X...X...XXXXX..X..X
  XXXXXXXXXXXXXXXXXX...X...X...XXXXX..X..X
  XXXXXXXXXXXXXXXXXX...X...X...XXXXX..X..X
  XXXXXXXXXXXXXXXXXX...X...X...XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXX...X...X...XXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
end
  return
__sub_Skyline45
  bkcolors:
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
  $76
end
  pfcolors:
  $00
  $00
  $00
  $00
  $00
  $00
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
  $70
end
  playfield:
  ................................................................................
  ................................................................................
  ................................................................................
  ................................................................................
  ................................................................................
  ................................................................................
  .....................................................X..........................
  .....................................................X..........................
  ....................................................XX..........................
  ....................................................XX..........................
  ....................................................XX..........................
  ....................................................XX..........XXX.............
  ...........XXXXX...........X........................XX..........XXX.............
  ...........XXXXX..........XX........................XX..........XXX.............
  ...........XXXXX.........XXX........................XX..........XXX.............
  ...........XXXXX........XXXX........................XX..........XXX.............
  ...........XXXXX.......XXXXX........................XX..........XXX.............
  ...........XXXXX......XXXXXX........................XX.........XXXXX............
  ...........XXXXX.....XXXXXXX........................XX.........XXXXX............
  ...........XXXXX....XXXXXXXX........................XX.........XXXXX............
  ...........X.X.X...XXXXXXXXX........................XX.........XXXXX............
  ...........X.X.X..XXXXXXXXXX........................XX.........XXXXX............
  ...........X.X.X..XXXXXXXXXX........................XX.........XXXXX............
  ...........X.X.X..XXXXXXXXXX........................XX.........XXXXX............
  ...........X.X.X..XXXXXXXXXX........................XX.....XXXXXXXXXXXXX........
  ...........X.X.X..XXXXXXXXXX........................XX.....XXXXXXXXXXXXX........
  ...........X.X.X..XXXXXXXXXX........................XX.....X...X...X...X........
  ...........X.X.X..X.....X..X........................XX.....X...X...X...X........
  ...........XX.XX..X.....X..X........................XX....XX...X...X...X........
  ...........XX.XX..X.....X..X........................XX....XX...X...X...X........
  ...........XX.XX..X.....X..X........................XX....XX...X...X...X........
  ...........XX.XX..X.....X..X........................XX...XXX...X...X...X........
  ...........XX.XX..X.....X..X........................XX...XXX...X...X...X........
  ...........XX.XX..X.....X..X...XXXXX................XX...XXX...X...X...X........
  ...........XX.XX..X.....X..X...XXXXX..............XXXXXXXXXXXXXXXXXXXXXXX.......
  ...........XX.XX..X.....X..X...XXXXX..............XXXXXXXXXXXXXXXXXXXXXXX.......
  ...........X.X.X..X.....X..X...XXXXX...............XXXXX...X...X...X...X........
  ...........X.X.X..X.....X..X...XXXXX...............XXXXX...X...X...X...X........
  ...........X.X.X..X.....X..X...XXXXX...............XXXXX...X...X...X...X........
  ...........X.X.X..X.....X..X...XXXXX...............XXXXX...X...X...X...X........
  ...........X.X.X..X.....X..X...XXXXX...............XXXXX...X...X...X...X........
  ...........X.X.X..XXXXXXXXXX..XX.X.XX..............XXXXX...X...X...X...X........
  ...X..X..X.X.X.X..XXXXXXXXXX..XX.X.XX..............XXXXX...X...X...X...X........
  ...X..X..X.X.X.X..XXXXXXXXXX..XX.X.XX..............XXXXX...X...X...X...X........
  ...X.XXX.X.XX.XX..XXXXXXXXXX..XX.X.XX..........XXXXXXXXXXXXXXXXXXXXXXXXXX.......
  ...X.XXX.X.XX.XX..XXXXXXXXXX..XX.X.XX..........XXXXXXXXXXXXXXXXXXXXXXXXXX.......
  ...XXXXXXX.XX.XX..XXXXXXXXXX..XX.X.XX...........X.X.X.X.X.X.X.X.X.X.X.X.X.......
  ...XXXXXXX.XX.XX..X..X.....X..XX.X.XX...........X.X.X.X.X.X.X.X.X.X.X.X.X.......
  ...XXXXXXX.XX.XX..X..X.....X.XXXXXXXXX..........X.X.X.X.X.X.X.X.X.X.X.X.X.......
  ...XXXXXXX.XX.XX..X..X.....X.XXXXXXXXX..........X.X.X.X.X.X.X.X.X.X.X.X.X.......
  ...XXXXXXX.XX.XX..X..X.....X.XXXXXXXXX..........X.X.X.X.X.X.X.X.X.X.X.X.X.......
  ...XXXXXXX.XX.....X..X.....X.XXXXXXXXX..........X.X.X.X.X.X.X.X.X.X.X.X.X.......
  ...XXXXXXX.X.X....X..X.....X.XXXXXXXXX..........X.X.X.X.X.X.X.X.X.X.X.X.X.......
  ...XXXXXXX.X.XXXXXX..X.....X.XXXXXXXXX..........X.X.X.X.X.X.X.X.X.X.X.X.X.......
  ...XXXXXXX.X.XXXXXX..X.....X.XXXXXXXXX........XXXXXXXXXXXXXXXXXXXXXXXXXXXX......
  ...XXXXXXX.X.XXXXXX..X.....X.XXXXXXXXX........XXXXXXXXXXXXXXXXXXXXXXXXXXXX......
  ...X..X..X.X.XXXXXX..X.....X.X.X.X.X.X.........X.X.X.X.X.X.X.X.X.X.X.X.X.X......
  ...X..X..X.X.XXXXXX..X.....X.X.X.X.X.X.........X.X.X.X.X.X.X.X.X.X.X.X.X.X......
  ...X..X..X.X.XXXXXX..X.....X.X.X.X.X.X.........X.X.X.X.X.X.X.X.X.X.X.X.X.X......
  ...X..X..X.X.XXXXXX..X.....X.X.X.X.X.X.........X.X.X.X.X.X.X.X.X.X.X.X.X.X......
  ...X..X..X.XX.XXXXX..X.....X.X.X.X.X.X.........X.X.X.X.X.X.X.X.X.X.X.X.X.X......
  ...X..X..X.XX.X.X.XXXXXXXXXX.X.X.X.X.X.........X.X.X.X.X.X.X.X.X.X.X.X.X.X......
  ...X..X..X.XX.X.X.XXXXXXXXXX.X.X.X.X.X.........X.X.X.X.X.X.X.X.X.X.X.X.X.X......
  ...X..X..X.XX.X.X.XXXXXXXXXX.XXXXXXXXX.........X.X.X.X.X.X.X.X.X.X.X.X.X.X......
  ...XXXXXXX.XX.X.X.XXXXXXXXXX.XXXXXXXXX........XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....
  ...XXXXXXX.XX.X.X.XXXXXXXXXX.XXXXXXXXX........XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....
  ...XXXXXXX.XX.X.X.XXXXXXXXXX.XXXXXXXXX.........XX.X.X.X.X.X.X.X.X.X.X.X.X.X.....
  ...XXXXXXX.XX.X.X.X.....X..X.XXXXXXXXX.........XX.X.X.X.X.X.X.X.X.X.X.X.X.X.....
  ...XXXXXXX.X.XX.X.X.....X..X.XXXXXXXXX.........XX.X.X.X.X.X.X.X.X.X.X.X.X.X.....
  ...XXXXXXX.X.XX.X.X.....X..X.XXXXXXXXX.........XX.X.X.X.X.X.X.X.X.X.X.X.X.X.....
  ...XXXXXXX.X.XX.X.X.....X..X.X.X.X.X.X.........XX.X.X.X.X.X.X.X.X.X.X.X.X.X.....
  ...XXXXXXX.X.XX.X.X.....X..X.X.X.X.X.X.........XX.X.X.X.X.X.X.X.X.X.X.X.X.X.....
  ...X..X..X.X.XX.X.X.....X..X.X.X.X.X.X.........XX.X.X.X.X.X.X.X.X.X.X.X.X.X.....
  ...X..X..X.X.XX.X.X.....X..X.X.X.X.X.X.........XX.X.X.X.X.X.X.X.X.X.X.X.X.X.....
  ...X..X..X.X.XX.X.X.....X..X.X.X.X.X.X........XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....
  ...X..X..X.X..X.X.X.....X..X.X.X.X.X.X........XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....
  ...X..X..X.X..X.X.X.....X..X.X.X.X.X.X.........X.X.X.X.X.X.X.X.X.X.X.X.X.XX.....
  ...X..X..X.XXXXXXXX.....X..X.XXXXXXXXX.........X.X.X.X.X.X.X.X.X.X.X.X.X.XX.....
  ...X..X..X.XXXXXXXX.....X..X.XXXXXXXXX.........X.X.X.X.X.X.X.X.X.X.X.X.X.XX.....
  ...X..X..X.XXXXXXXX.....X..X.XXXXXXXXX.........X.X.X.X.X.X.X.X.X.X.X.X.X.XX.....
  ...XXXXXXX.XXXXXXXX.....X..X.XXXXXXXXX.........X.X.X.X.X.X.X.X.X.X.X.X.X.XX.....
  ...XXXXXXX.XXXXXXXXXXXXXXXXX.XXXXXXXXX.........X.X.X.X.X.X.X.X.X.X.X.X.X.XX.....
  ...XXXXXXX.XXXXXXXXXXXXXXXXX.XXXXXXXXX.........X.X.X.X.X.X.X.X.X.X.X.X.X.XX.....
  ...XXXXXXX.XXXXXXXXXXXXXXXXX.XXXXXXXXX.........X.X.X.X.X.X.X.X.X.X.X.X.X.XX.....
  ...XXXXXXX.XXXXXXXXXXXXX......................XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....
  ...XXXXXXX.XX.X.X.XXXXXX......................XXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....
  ...XXXXXXX.XX.X.X.XXXXXXXXXXXXXXXXXXXXXX........................................
  ...XXXXXXX.XX.X.X.X..X..XXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..
  ...X..X..X.XX.X.X.X..X..XXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..
  ...X..X..X.XX.X.X.X..X..XXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..
  ...X..X..X.XX.X.X.X..X..XXXXXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..
  ...X..X..X.XX.X.X.X..X..XXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...
  ...X..X..X.XX.X.X.X..X..XXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...
  ...X..X..X.XX.X.X.X..X..X..X..X..X..X..X.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...
  ...X..X..X.XX.X.X.X..X..X..X..X..X..X..X.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...
  ...X..X..X.XX.X.X.X..X..X..X..X..X..X..X.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....
  ...XXXXXXX.XX.X.X.X..X..X..X..X..X..X..X.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....
  ...XXXXXXX.XX.X.X.X..X..X..X..X..X..X..X.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....
  ...XXXXXXX.XX.X.X.X..X..X..X..X..X..X..X.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX....
  ...XXXXXXX..X.X.X.X..X..X..X..X..X..X..X.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....
  ...XXXXXXX..X.X.X.X..X..X..X..X..X..X..X.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....
  ...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....
  ...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....
  ...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXX......
  ...X..X..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXX......
  ...X..X..XXXXXXXXXXXXXXXX..X..X..X..XXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXX......
  ...X..X..XXXXXXXXXXXXXXXX..X..X..X..XXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXX......
  ...X..X..XXXXXXXXXX.....X..X..X..X..XXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXX.......
  ...X..X..XXXXXXXXXX.....X..X..X..X..XXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXX.......
  ...X..X..XXXXXXXXXX.....X..X..X..X..XXXX........................................
  ...X..X..XX.X.X.X.X.....X..X..X..X..XXXX........................................
  ...X..X..XX.X.X.X.X.....X..X..X..X..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  ...XXXXXXXX.X.X.X.X.....X..X..X..X..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  ...XXXXXXXX.X.X.X.X.....XXXXXXXXXXXXX.......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  ...XXXXXXXX.X.X.X.X.....XXXXXXXXXXXXX.....XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  ...XXXXXXXX.X.X.X.X.....XXXXXXXXXXXXX.......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  ...XXXXXXXX.X.X.X.X.....XXXXXXXXXXXXX......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  ...XXXXXXXX.X.X.X.X.....XXXXXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  ...XXXXXXXXXXXXXXXX.....XXXXXXXXXXXXX.......XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  ...XXXXXXXXXXXXXXXX.....XXXXXXXXXXXX.........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  ...XXXXXXXXXXXXXXXX.....XXXXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  ...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XX.......XXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXX
  ...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XX......XXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXX
  ...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XX.......XXXXXXXXXXXXXXXXXXXXXXXXXX.X.XXXXX
  ...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XX......XXXXXXXXXXXXXXXXXXXXXXXXXXX.X.XXXXX
  ...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XX.......XXXXXXXXXXXXXXXXXXXXXXXXXX.X.XXXXX
  ...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XX........XXXXXXXXXXXXXXXXXXXXXXXXXX.X.XXXX
  ..............................................XXXXXXXXXXXXXXXXXXXXXXXXXXX.X.XXXX
  ...............................................XXXXXXXXXXXXXXXXXXXXXXXX...XXXXXX
  ...XXXXXXXXXXXX.XXXXXXXXXXX.XXXXXXXXXXX.......XXXXXXXXXXXXXXXXXXXXXXXXX...XXXXXX
  ...XXXXXXXXXXXX.XXXXXXXXXXX.XXXXXXXXXXX.........XXXXXXXXXXXXXXXXXXXXXXX.X..XXXXX
  ...XXXXXXXXXXXX.XXXXXXXXXXX.XXXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXXXX..X..XXXXX
  ...XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.........XXXXXXXXXXXXXXXXXXXXXX.XX.X.XXXX
  ..XXXXXXXXXXXXX.XXXXXXXXXXX.XXXXXXXXXXX........XXXXXXXXXXXXXXXXXXXXXXX.XX.X.XXXX
  ..X.X.X.X.X.X.XXX.X.X.X.X.XXX.X.X.X.X.X.........XXXXXXXXXXXXXXXXXXXXXX.XX.X.XXXX
  ..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.........XXXXXXXXXXXXXXXXXXXXXXXXX.X.XXXX
  ..X.X.X.X.X.X.XXX.X.X.X.X.XXX.X.X.X.X.X..........XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX
  .X..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.........XXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX
  .X..X.X.X.X.X.XXX.X.X.X.X.XXX.X.X.X.X.X..........XXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX
  .X..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.........XXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXX
  .X..X.X.X.X.X.XXX.X.X.X.X.XXX.X.X.X.X.X..........XXXXXXXXXXXXXXXXXXXXXXX..XXXXXX
  .X..X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..........XXXXXXXXXXXXXXXXXXXXXXX..XXXXXX
  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXX.XXXXXXX
  .XXXXXXXXXXXXXX.XXXXXXXXXXX.XXXXXXXXXXX..........XXXXXXXXXXXXXXXXXXXXXXX.XXXXXXX
  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXX.XXXXXXX
  .XXXXXXXXXXXXXX.XXXXXXXXXXX.XXXXXXXXXXX..........XXXXXXXXXXXXXXXXXXXXXXX.XXXXXXX
  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX............XXXXXXXXXXXXXXXXXXXXX.XXXXXXX
  .XXXXXXXXXXXXXX.XXXXXXXXXXX.XXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXX.XXXXXXX
  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX............XXXXXXXXXXXXXXXXXXXXX.XXXXXXX
  ..XXXXXXXXXXXXX.XXXXXXXXXXX.XXXXXXXXXXX...........XXXXXXXXXXXXXXXXXXXXXX.XXXXXXX
  ..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX............XXXXXXXXXXXXXXXXXXXXX.XXXXXXX
  ...XXXXXXXXXXXX.XXXXXXXXXXX.XXXXXXXXXXX............XXXXXXXXXXXXXXXXXXXXX.XXXXXXX
  ....................................................XXXXXXXXXXXXXXXXXXXX.XXXXXXX
  ...................................................XXXXXXXXXXXXXXXXXXX...XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.............XXXXXXXXXXXXXXXX.....XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX............XXXXXXXXXXXXXXXX.......XXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.............XXXXXXXXXXXXXXX...X....XXXXX
  X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X................XXXXXXXXXXXXXXX.....X....XXXX
  X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.................XXXXXXXXXXXXXX.....XX...XXXX
  X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.................XXXXXXXXXXXXXX..XX..X...XXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.................XXXXXXXXXXXXX..........XXXX
  .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X................XXXXXXXXXXXXXXX........XXXXX
  .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.................XXXXXXXXXXXXXX........XXXXX
  .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X................XXXXXXXXXXXXXXXXX....XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.................XXXXXXXXXXXXXXXXXXXXXXXXXXX
  X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.................XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..................XXXXXXXXXXXXXXXXXXXXXXXXXXX
  X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.................XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..................XXXXXXXXXXXXXXXXXXXXXXXXXX
  .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.................XXXXXXXXXXXXXXXXXXXXXXXXXXX
  .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X..................XXXXXXXXXXXXXXXXXXXXXXXXXX
  .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.................XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..................XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.................XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..................XXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.................XXXXXXXXXXXXXXXXXXXXXXXXXXX
end
  return
; **************** END AUTO GENERATED - DO NOT EDIT  ****************
